routes/web.php
<?php
use Illuminate\Http\Request;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function(){
    return view('mainpage.login');
});
Route::post('/login',function(Request $req){
    if($req->username == "admin" && $req->password == "admin"){
        return redirect()->route('admin.dashboard');
    }else{
        return redirect()->back()->with('errors','Username / Password Salah!');
    }
})->name('auth.login');

Route::prefix('admin')->group(function(){
    Route::get('/',function(){
        return view('mainpage.admin');
    })->name("admin.dashboard");
    Route::get('/inventory',function(){
        return view('inventory.index');
    })->name('inventory.index');
    Route::get('/checkin',function(){
        return view('checkin.index');
    })->name('checkin.index');
});

app/Models/Event.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;
use Storage;

class Event extends Model
{
    public function getTglEventAttribute(){
        return Carbon::parse($this->tgl_mulai)->format('d/m/Y') . " - " . Carbon::parse($this->tgl_selesai)->format('d/m/Y');
    }
    public function getThumbnailImgAttribute(){
        return Storage::disk('public')->url($this->thumbnail);
    }
}

resources/views/layouts/partials/footer.blade.php
<footer>
    <div class="container-fluid footer-list">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-8">
                    <ul>
                        <h4>Tujuan Wisata</h4>
                        <li><a href="{{ route('main.pariwisata','curug-bandung') }}">Curug Bandung</a></li>
                        <li><a href="{{ route('main.pariwisata','pantai-tanjung-baru') }}">Pantai Tanjung Baru</a></li>
                        <li><a href="{{ route('main.pariwisata','danau-cipuler') }}">Danau Cipule</a></li>
                        <li><a href="{{ route('main.pariwisata','candi-jiwa') }}">Candi Jiwa</a></li>
                        <li><a href="{{ route('main.pariwisata','pantai-sedari') }}">Pantai Sedari</a></li>
                        <li><a href="{{ route('main.pariwisata','bukit-kembar') }}">Bukit Kembar</a></li>
                        <li><a href="{{ route('main.pariwisata','pantai-samudera-baru') }}">Pantai Samudera Baru</a></li>
                        <li><a href="{{ route('main.pariwisata','green-canyon') }}">Green Canyon</a></li>
                        <li><a href="{{ route('main.pariwisata','taruma-leisure-waterpark') }}">Taruma Leisure Waterpark</a></li>
                    </ul>

                    <ul>
                        <h4>Interes</h4>
                        <li><a href="#">Petualangan</a></li>
                        <li><a href="#">Wisata Keluarga</a></li>
                        <li><a href="#">Festival & events</a></li>
                        <li><a href="#">Makanan & Minuman</a></li>
                        <li><a href="#">Pantai</a></li>
                        <li><a href="#">Wisata Alam</a></li>
                        <li><a href="#">Diving & snorkeling</a></li>
                    </ul>

                    <ul>
                        <h4>Media Center</h4>
                        <li><a href="#">Foto</a></li>
                        <li><a href="#">Video</a></li>
                        <li><a href="#">Press</a></li>
                    </ul>
                </div>
                <div class="col-sm-4 col-md-4 footer-form">
                    <h4>Berlangganan Tabloid Disbudpar</h4>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
                    <form>
                        <input class="form-control" type="email" name="" maxlength="100">
                        <button type="submit" class="btn">Daftar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid footer-cp">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <a href="#" class="footer-logo">
                        <h2>Pariwisata<br><span>Karawang</span></h2>
                    </a>
                    <ul>
                        <li><a href="#">About us</a></li>
                        <li><a href="#">Terms & Conditions</a></li>
                        <li><a href="#">Privacy Policy</a></li>
                        <li><a href="{{ route('main.kontak') }}">Contact us</a></li>
                        <span>&copy; 2016 Disparbud Kab. Karawang, Jawa Barat - Indonesia</span>
                    </ul>
                </div>
            </div>
        </div>
    </div>

</footer>

resources/views/layouts/partials/informasi_lainnya.blade.php
<section id="useful-info">
    <div class="container   ">
        <div class="section-h">
            <h2>Informasi bermanfaat Lainnya</h2>
        </div>

        <div class="row">
            @foreach($berita as $item)
            <div class="col-sm-4 col-md-4">
                <a href="{{ route('main.berita.detail',$item->id) }}" class="box-imgdesc">
                    <div class="imgboard">
                        <img src="{{ asset($item->thumbnail_img) }}" class="img-responsive">
                    </div>
                    <div class="desc">
                        <h4>{{ $item->judul }}</h4>
                        {!! $item->konten !!}
                    </div>
                </a>
            </div>
            @endforeach
        </div>
    </div>
</section>

resources/views/layouts/partials/promosi.blade.php
<div class="col-sm-3 col-md-3">
        <div class="sidenav">

            <a href="#" class="side-box-imgdesc">
                <div class="imgboard">
                    <img src="{{ asset('/assets/img/slides/karawang_pantai-tanjung-pakis.png') }}" class="img-responsive">
                </div>
                <div class="desc">
                    <h5>Banner promosi</h5>
                    <p>Duis dolor est, tincidunt vel enim sit amet, venenatis euismod neque. Duis
                        eleifend ligula id tortor finibus faucibus. Donec et quam pulvinar, blandit
                        tortor. ...</p>
                </div>
            </a>

            <ul>
                <h4>Tujuan Wisata Populer:</h4>
                <li><a href="curug-bandung.html">Curug Bandung</a></li>
                <li><a href="curug-bandung.html">Pantai Tanjung Baru</a></li>
                <li><a href="curug-bandung.html">Danau Cipule</a></li>
                <li><a href="curug-bandung.html">Candi Jiwa</a></li>
                <li><a href="curug-bandung.html">Pantai Sedari</a></li>
                <li><a href="curug-bandung.html">Bukit Kembar</a></li>
                <li><a href="curug-bandung.html">Pantai Samudera Baru</a></li>
                <li><a href="curug-bandung.html">Green Canyon</a></li>
                <li><a href="curug-bandung.html">Taruma Leisure Waterpark</a></li>
            </ul>
        </div>
    </div>

resources/views/layouts/partials/sidebar.blade.php
<!-- begin:: Aside -->
<div class="kt-aside__brand kt-grid__item " id="kt_aside_brand">
    <div class="kt-aside__brand-logo">
        <a href="{{ url('/') }}" class="animated1 fadeIn">
            <h3>RFID Inventory Management</h3>
        </a>
    </div>
    <div class="kt-aside__brand-tools">
        <button class="kt-aside__brand-aside-toggler" id="kt_aside_toggler">
            <span><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px"
                    height="24px" viewBox="0 0 24 24" version="1.1" class="kt-svg-icon">
                    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                        <polygon id="Shape" points="0 0 24 0 24 24 0 24" />
                        <path
                            d="M5.29288961,6.70710318 C4.90236532,6.31657888 4.90236532,5.68341391 5.29288961,5.29288961 C5.68341391,4.90236532 6.31657888,4.90236532 6.70710318,5.29288961 L12.7071032,11.2928896 C13.0856821,11.6714686 13.0989277,12.281055 12.7371505,12.675721 L7.23715054,18.675721 C6.86395813,19.08284 6.23139076,19.1103429 5.82427177,18.7371505 C5.41715278,18.3639581 5.38964985,17.7313908 5.76284226,17.3242718 L10.6158586,12.0300721 L5.29288961,6.70710318 Z"
                            id="Path-94" fill="#000000" fill-rule="nonzero"
                            transform="translate(8.999997, 11.999999) scale(-1, 1) translate(-8.999997, -11.999999) " />
                        <path
                            d="M10.7071009,15.7071068 C10.3165766,16.0976311 9.68341162,16.0976311 9.29288733,15.7071068 C8.90236304,15.3165825 8.90236304,14.6834175 9.29288733,14.2928932 L15.2928873,8.29289322 C15.6714663,7.91431428 16.2810527,7.90106866 16.6757187,8.26284586 L22.6757187,13.7628459 C23.0828377,14.1360383 23.1103407,14.7686056 22.7371482,15.1757246 C22.3639558,15.5828436 21.7313885,15.6103465 21.3242695,15.2371541 L16.0300699,10.3841378 L10.7071009,15.7071068 Z"
                            id="Path-94" fill="#000000" fill-rule="nonzero" opacity="0.3"
                            transform="translate(15.999997, 11.999999) scale(-1, 1) rotate(-270.000000) translate(-15.999997, -11.999999) " />
                    </g>
                </svg></span>
            <span><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px"
                    height="24px" viewBox="0 0 24 24" version="1.1" class="kt-svg-icon">
                    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                        <polygon id="Shape" points="0 0 24 0 24 24 0 24" />
                        <path
                            d="M12.2928955,6.70710318 C11.9023712,6.31657888 11.9023712,5.68341391 12.2928955,5.29288961 C12.6834198,4.90236532 13.3165848,4.90236532 13.7071091,5.29288961 L19.7071091,11.2928896 C20.085688,11.6714686 20.0989336,12.281055 19.7371564,12.675721 L14.2371564,18.675721 C13.863964,19.08284 13.2313966,19.1103429 12.8242777,18.7371505 C12.4171587,18.3639581 12.3896557,17.7313908 12.7628481,17.3242718 L17.6158645,12.0300721 L12.2928955,6.70710318 Z"
                            id="Path-94" fill="#000000" fill-rule="nonzero" />
                        <path
                            d="M3.70710678,15.7071068 C3.31658249,16.0976311 2.68341751,16.0976311 2.29289322,15.7071068 C1.90236893,15.3165825 1.90236893,14.6834175 2.29289322,14.2928932 L8.29289322,8.29289322 C8.67147216,7.91431428 9.28105859,7.90106866 9.67572463,8.26284586 L15.6757246,13.7628459 C16.0828436,14.1360383 16.1103465,14.7686056 15.7371541,15.1757246 C15.3639617,15.5828436 14.7313944,15.6103465 14.3242754,15.2371541 L9.03007575,10.3841378 L3.70710678,15.7071068 Z"
                            id="Path-94" fill="#000000" fill-rule="nonzero" opacity="0.3"
                            transform="translate(9.000003, 11.999999) rotate(-270.000000) translate(-9.000003, -11.999999) " />
                    </g>
                </svg></span>
        </button>

        <!--<button class="kt-aside__brand-aside-toggler kt-aside__brand-aside-toggler--left" id="kt_aside_toggler"><span></span></button>-->
    </div>
</div>

<!-- end:: Aside -->
<!-- begin:: Aside Menu -->
<div class="kt-aside-menu-wrapper kt-grid__item kt-grid__item--fluid" id="kt_aside_menu_wrapper">
    <div id="kt_aside_menu" class="kt-aside-menu " data-ktmenu-vertical="1" data-ktmenu-scroll="1"
        data-ktmenu-dropdown-timeout="500">
        <ul class="kt-menu__nav ">
            <li class="kt-menu__item kt-menu__item--active" aria-haspopup="true">
                <a href="#" class="kt-menu__link ">
                    <span class="kt-menu__link-icon">
                        <i class="flaticon-analytics"></i>
                    </span>
                    <span class="kt-menu__link-text">Dashboard</span>
                </a>
            </li>
            <li class="kt-menu__item kt-menu__item--active" aria-haspopup="true">
                <a href="{{ route('checkin.index') }}" class="kt-menu__link ">
                    <span class="kt-menu__link-icon">
                        <i class="flaticon-folder-2"></i>
                    </span>
                    <span class="kt-menu__link-text">Check In</span>
                </a>
            </li>
            <li class="kt-menu__item" aria-haspopup="true">
                <a href="#" class="kt-menu__link ">
                    <span class="kt-menu__link-icon">
                        <i class="flaticon-folder-3"></i>
                    </span>
                    <span class="kt-menu__link-text">Check Out</span>
                </a>
            </li>
            <li class="kt-menu__item kt-menu__item--active" aria-haspopup="true">
                <a href="{{ route('inventory.index') }}" class="kt-menu__link ">
                    <span class="kt-menu__link-icon">
                        <i class="flaticon-home"></i>
                    </span>
                    <span class="kt-menu__link-text">Inventory</span>
                </a>
            </li>
            <li class="kt-menu__item kt-menu__item--active" aria-haspopup="true">
                <a href="#" class="kt-menu__link ">
                    <span class="kt-menu__link-icon">
                        <i class="fas fa-print"></i>
                    </span>
                    <span class="kt-menu__link-text">Print Label</span>
                </a>
            </li>
            <li class="kt-menu__item kt-menu__item--active" aria-haspopup="true">
                <a href="#" class="kt-menu__link ">
                    <span class="kt-menu__link-icon">
                        <i class="flaticon-folder"></i>
                    </span>
                    <span class="kt-menu__link-text">Master Data</span>
                </a>
            </li>
            <li class="kt-menu__item kt-menu__item--active" aria-haspopup="true">
                <a href="#" class="kt-menu__link ">
                    <span class="kt-menu__link-icon">
                        <i class="flaticon-clipboard"></i>
                    </span>
                    <span class="kt-menu__link-text">Log</span>
                </a>
            </li>
            <li class="kt-menu__item kt-menu__item--active" aria-haspopup="true">
                <a href="#" class="kt-menu__link ">
                    <span class="kt-menu__link-icon">
                        <i class="flaticon-customer"></i>
                    </span>
                    <span class="kt-menu__link-text">Help</span>
                </a>
            </li>
            <li class="kt-menu__item kt-menu__item--active" aria-haspopup="true">
                <a href="{{ url('/') }}" class="kt-menu__link ">
                    <span class="kt-menu__link-icon">
                        <i class="flaticon-logout"></i>
                    </span>
                    <span class="kt-menu__link-text">Logout</span>
                </a>
            </li>
        </ul>
    </div>
</div>
<!-- end:: Aside Menu -->

resources/views/layouts/partials/topnav.blade.php
<div class="topnav">
        <ul class="nav">
            <li class="dropdown dropdown-hover">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Tentang kami</a>
                <ul class="dropdown-menu root">
                    <li><a href="#">Pariwisata Indonesia</a></li>
                    <li><a href="#">Penghargaan</a></li>
                    <li><a href="{{ route('main.kontak') }}">Hubungi kami</a></li>
                </ul>
            </li>
            <li class="dropdown dropdown-hover">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Tujuan Wisata</a>
                <ul class="dropdown-menu root">
                    <li>
                        <a href="{{ route('main.pariwisata','curug-bandung') }}">
                            <div class="thumbox">
                                <img src="{{ asset('/assets/img/dests/thumb/th-curug-bandung.jpg') }}" class="img-responsive">
                            </div>
                            <span>Curug Bandung</span>
                        </a>
                    </li>
                    <li>
                        <a href="{{ route('main.pariwisata','pantai-tanjung-baru') }}">
                            <div class="thumbox">
                                <img src="{{ asset('/assets/img/dests/thumb/th-pantai-tanjung-baru.jpg') }}" class="img-responsive">
                            </div>
                            <span>Pantai Tanjung Baru</span>
                        </a>
                    </li>
                    <li>
                        <a href="{{ route('main.pariwisata','danau-cipule') }}">
                            <div class="thumbox">
                                <img src="{{ asset('/assets/img/dests/thumb/th-situ-cipule.jpg') }}" class="img-responsive">
                            </div>
                            <span>Danau Cipule</span>
                        </a>
                    </li>
                    <li>
                        <a href="{{ route('main.pariwisata','candi-jiwa') }}">
                            <div class="thumbox">
                                <img src="{{ asset('/assets/img/dests/thumb/th-candi-jiwa.jpg') }}" class="img-responsive">
                            </div>
                            <span>Candi Jiwa</span>
                        </a>
                    </li>
                    <li>
                        <a href="{{ route('main.pariwisata','green-canyon') }}">
                            <div class="thumbox">
                                <img src="{{ asset('/assets/img/dests/thumb/th-green-canyon.jpg') }}" class="img-responsive">
                            </div>
                            <span>Green Canyon</span>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <div class="thumbox">
                                <img src="{{ asset('/assets/img/dests/thumb/th-explore.jpg') }}" class="img-responsive">
                            </div>
                            <span>Lainnya...</span>
                        </a>
                    </li>
                </ul>
            </li>
            <li><a href="#">Seni & Budaya</a></li>
            <li><a href="{{ route('main.event') }}">Event</a></li>
            <li><a href="{{ route('main.berita') }}">Berita</a></li>
            <li><a href="{{ route('main.kontak') }}">Kontak</a></li>
            <!-- <li class="dropdown dropdown-hover">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">Media Center</a>
      <ul class="dropdown-menu root">
        <li><a href="#">Photo</a></li>
        <li><a href="#">Video</a></li>
        <li><a href="#">Press</a></li>
      </ul>
    </li>
    <li><a href="#">Maps</a></li> -->
        </ul>
    </div>
    <!-- </div> -->